### ISSUE TITLE
EDA discussion

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/canadian_heritage_funding#6]
Opening this issue to discuss which plots are necessary or what should be changed to show that our data is appropriate for our analysis/prediction.

We should also discuss whether the quantiles used so far are appropriate.

[See EDA plots here ](https://github.com/UBC-MDS/canadian_heritage_funding/blob/main/eda/eda_heritage_data.ipynb)

**Comment by artanzand** [comment]
EDA checklist from Art of Data Science:
1. Formulate your question
2. Read in your data
3. Check the packaging
4. Look at the top and the bottom of your data
5. Check your “n”s
6. Validate with at least one external data source
7. Make a plot
8. Try the easy solution first
9. Follow up

**Comment by artanzand** [comment]
- I recommend adding `heritage.describe()` right after `heritage.info()` . 
- sorting unique values for our numeric target does not add much intuition. Maybe we could take it out.
- I wonder whether exploding `disciplines` and `audiances` columns is a good idea because it has tripled the data size (from 1358 rows to 4681). This way we are adding extra weight to the features of observations that have multiple categories in these two columns.

**Comment by jo4356** [comment]
Maybe we can use CountVectorizer on those two columns when we build the model.  I'm not sure how else to plot those two column without exploding those two columns however.

**Comment by artanzand** [comment]
> Maybe we can use CountVectorizer on those two columns when we build the model. I'm not sure how else to plot those two column without exploding those two columns however.

Maybe just make a copy of the dataframe and and do your `.explode` operation there to create two separate plots. Yes, we can apply count vectorizer on those two columns for sure.

**Comment by jo4356** [comment]
What do you mean by two separate plots? with explosion and without explosion? Without explosion the plots look like this:
![visualization](https://user-images.githubusercontent.com/90012041/142708532-8de67f64-a476-423e-bc7d-a1e4e0bc7687.png)

**Comment by artanzand** [comment]
> What do you mean by two separate plots? with explosion and without explosion? Without explosion the plots look like this: ![visualization](https://user-images.githubusercontent.com/90012041/142708532-8de67f64-a476-423e-bc7d-a1e4e0bc7687.png)
> 
> So far I've settled with making a note under the plot saying that there are repeats in the data.

Sorry, I should have been more clear. What I meant was that from 10 categorical columns do the grid plot for the 8 regular ones separately, and then create a copy of your df, perform the `.explode` and create bar charts for the remaining two columns of `disciplines` and `audiences`.

**Comment by artanzand** [comment]
If you see any discrepancies in the results that I report below it is because I have used the original (1358 rows) for EDA:
- For your `mark_bar` plot before counts of features, I recommend adding `bin=alt.Bin(maxbins=150)` to `alt.X()` in order to make it a histogram (binned). bar charts are usually used for categorical data and we are dealing with numeric.
- For the Count of Features section, you get much readable labels if you swap alt.X with alt.Y . You may use this for the 8 categorical plots and drop the other two as mentioned in the issue above.
- Thought: For the bar chart with the cities name and the point chart with amount - Could you please swap the X and Y axis and change the width and height respectively.

**Comment by jo4356** [comment]
Ok. I made a pull request after these changes.

**Comment by artanzand** [comment]
Thank you Joyce! These all look good. Having experience with these funding I thought we could add another graphic with title: "Fixed pooled funding per discipline". This shows that the amount of funding a project receives is well dependent on the type of project.
```
eda4 = (
    alt.Chart(heritage).mark_bar().encode(
        alt.X("disciplines", type="ordinal"),
        alt.Y("count()"),
        alt.Color("greater_than:O"))
    .properties(width=200, height=150)
    .facet("fiscal_year", columns=1)
)
eda4
```
